config/routes.rb
Rails.application.routes.draw do
# mount ActiveStorage::Engine, at: "/audio" 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope :audio do
  root 'sessions#new'
  scope "(:locale)", locale: /en|ar|fr/ do 
    resources :sessions
    resources :homes
    resources :books do 
      get :setting, on: :member
      get :change_status, on: :member
    end
    resources :booths do
      get :setting, on: :member
    end
    resources :operations
    resources :categories  do
      get :setting, on: :member
    end
    resources :users do 
      get :setting, on: :member
      get :change_status, on: :member      
    end
    resources :reports

    get 'change_password/:auth_token',to: 'sessions#change_password', as: "change_password"
    get 'login', to: "sessions#new"

    namespace :web  do
      get "all_books", to: "books#all_books"
      get "play_book_for_blind", to: "books#play_book_for_blind"
      
      resources :booths, only: [:index, :show]  do
        resources :books, only: [:index, :show] do
          get :search, on: :collection
          get :category_search, on: :collection
          get :accessibility_mode, on: :collection
          get :children_mode, on: :collection
        end
      end
      resources :operations, only: [] do
        get :media_files, on: :member
        get :update_listen_count, on: :member
        put :save_feedback, on: :member
      end
    end
  end
  end 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :logged_in?
  before_action :set_book, except: [:new, :create, :index]
  before_action :ensure_book_present?, except: [:new, :create, :index]
  before_action :fetch_categories, only: [:index, :edit]
  before_action :validate_files, only: [:create, :update]
  before_action :validate_files_using_magic_number, only: [:create, :update]
  include Rails.application.routes.url_helpers

  def index
    url = "#{ENV["API_BASE_URL"]}/api/books"
    headers = {"Authorization": "Bearer #{session[:token]}"}
    response = HTTParty.get(url, body: params.as_json, headers: headers)
    response_body = JSON.parse(response.body) if response.body.present?
    return render_token_invalid_error if response_body.present? && response_body["status_code"] == 301

    if response_body.present? &&  response_body.dig("books").dig("data").present?
      @books =  response_body["books"]["data"]
      @pagination_data =  response_body["books"]["meta"]
    end
  end
  
  # def create
  #   @store = Store.new({
  #     model_type: "Book",
  #     name: params[:book][:title],
  #     book_cover_file: params[:book][:book_cover_file],
  #     audio: params[:book][:audio],
  #     short_audio_file: params[:book][:short_audio_file]
  #     })
  #     @store.save 
  #   url = "#{ENV["API_BASE_URL"]}/api/books"
  #   if params["book"].present?
  #     data = {}
  #     data["book"] = {}
  #     data["book"] = book_params
  #     data["book"]["category_ids"] = params["book"]["category_ids"]
  #     data["book"]["cover"] =  rails_blob_path(@store.book_cover_file, only_path: true) if params["book"]["book_cover_file"].present?
  #     data["book"]["long"] =  rails_blob_path(@store.audio, only_path: true) if params["book"]["audio"].present?
  #     data["book"]["short"] =  rails_blob_path(@store.short_audio_file, only_path: true) if params["book"]["short_audio_file"].present?
  #     # data["book"]["book_cover_file"] =  File.open(params["book"]["book_cover_file"].tempfile.path) if params["book"]["book_cover_file"].present?
  #     # data["book"]["audio"] =  File.open(params["book"]["audio"].tempfile.path) if params["book"]["audio"].present?
  #     # data["book"]["short_audio_file"] =  File.open(params["book"]["short_audio_file"].tempfile.path) if params["book"]["short_audio_file"].present?
  #   end
  #   headers = {headers: {"Content-Type": "application/json", "Authorization": "Bearer #{session[:token]}"},multipart: true, body: data}
  #   response = HTTParty.post(url, headers)
  #   response_body = JSON.parse(response.body) if response.body.present?
  #   @store.update(ref_id: response_body["book"]["data"]["id"].to_i)
  #   if response_body.present? &&  response_body.dig("book").dig("data").present?
  #     redirect_to books_path
  #   end
  # end

  def create
    url = "#{ENV["API_BASE_URL"]}/api/books"
    if params["book"].present?
      data = {}
      data["book"] = {}
      data["book"] = book_params
      data["book"]["category_ids"] = params["book"]["category_ids"]
      data["book"]["cover"] =  upload_file_path_for(params["book"]["book_cover_file"])  if params["book"]["book_cover_file"].present?
      data["book"]["longg"] = upload_file_path_for(params["book"]["audio"])  if params["book"]["audio"].present?
      data["book"]["short"] = upload_file_path_for(params["book"]["short_audio_file"]) if params["book"]["short_audio_file"].present?
      # data["book"]["book_cover_file"] =  File.open(params["book"]["book_cover_file"].tempfile.path) if params["book"]["book_cover_file"].present?
      # data["book"]["audio"] =  File.open(params["book"]["audio"].tempfile.path) if params["book"]["audio"].present?
      # data["book"]["short_audio_file"] =  File.open(params["book"]["short_audio_file"].tempfile.path) if params["book"]["short_audio_file"].present?
    end
    headers = {headers: {"Content-Type": "application/json", "Authorization": "Bearer #{session[:token]}"},multipart: true, body: data}
    response = HTTParty.post(url, headers)
    response_body = JSON.parse(response.body) if response.body.present?
    if response_body.present? &&  response_body.dig("book").dig("data").present?
      redirect_to books_path
    end
  end

  def update
    url = "#{ENV["API_BASE_URL"]}/api/books/#{params[:id]}"
    if params["book"].present?
      data = {}
      data["book"] = {}
      data["book"] = book_params
      data["book"]["category_ids"] = params["book"]["category_ids"]
      data["book"]["cover"] =  upload_file_path_for(params["book"]["book_cover_file"])  if params["book"]["book_cover_file"].present?
      data["book"]["longg"] = upload_file_path_for(params["book"]["audio"])  if params["book"]["audio"].present?
      data["book"]["short"] = upload_file_path_for(params["book"]["short_audio_file"]) if params["book"]["short_audio_file"].present?
      # data["book"]["book_cover_file"] =  File.open(params["book"]["book_cover_file"].tempfile.path) if params["book"]["book_cover_file"].present?
      # data["book"]["audio"] =  File.open(params["book"]["audio"].tempfile.path) if params["book"]["audio"].present?
      # data["book"]["short_audio_file"] =  File.open(params["book"]["short_audio_file"].tempfile.path) if params["book"]["short_audio_file"].present?
    end
    headers = {headers: {"Content-Type": "application/json", "Authorization": "Bearer #{session[:token]}"},multipart: true, body: data}
    response = HTTParty.put(url, headers)
    response_body = JSON.parse(response.body) if response.body.present?
    return render_token_invalid_error if response_body.present? && response_body["status_code"] == 301

    if response_body.present? &&  response_body.dig("book").dig("data").present?
      redirect_to books_path
    end
  end

  def show
  end

  def edit
  end

  def setting
  end

  def change_status
    url = "#{ENV["API_BASE_URL"]}/api/books/#{params[:id]}/change_status"
    headers = {headers: {"Content-Type": "application/json", "Authorization": "Bearer #{session[:token]}"},multipart: true, body: params.as_json}
    response = HTTParty.get(url, headers)
    response_body = JSON.parse(response.body) if response.body.present?
    return render_token_invalid_error if response_body.present? && response_body["status_code"] == 301

    if response_body.present? &&  response_body.dig("book").dig("data").present?
      redirect_to books_path
    end
  end
#working
  def destroy
    url = "#{ENV["API_BASE_URL"]}/api/books/#{params[:id]}"
    headers = {"Content-Type": "application/json", "Authorization": "Bearer #{session[:token]}"}
    response = HTTParty.delete(url, headers: headers)
    response_body = JSON.parse(response.body) if response.body.present?
    return render_token_invalid_error if response_body.present? && response_body["status_code"] == 301

    if response_body.present? &&  response_body["status_code"] == 200
      message = t("book_deleted_successfully")
      redirect_to books_path, notice: message
    else
      redirect_to books_path, notice: t("something_went_wrong")
    end
  end

  private

  def book_params
     params.require(:book).permit(:title, :language, :arabic_author_name, :arabic_title, :arabic_body, :author_name, :book_duration, :body,
      :user_id, :audio_type
    )
  end

  def set_book
    url = "#{ENV["API_BASE_URL"]}/api/books/#{params[:id]}"
    headers = {"Content-Type": "application/json", "Authorization": "Bearer #{session[:token]}"}
    response = HTTParty.get(url, headers: headers)
    response_body = JSON.parse(response.body) if response.body.present?
    return render_token_invalid_error if response_body.present? && response_body["status_code"] == 301

    if response_body.present? &&  response_body.dig("book").dig("data").present?
      @book = response_body["book"]["data"]["attributes"]
    end
  end

  def ensure_book_present?
    if @book.blank?
      redirect_to books_path, alert: t("booth_not_found")
    end
  end

  def ensure_category_present?
    @categories = Category.where(id: params[:book][:category_ids])
    if @categories.blank?
      redirect_to books_path, alert: t('category_not_valid')
    end
  end

  def update_category_record
    existing_category_id = @book.category_ids
    category_ids_for_remove = existing_category_id - @categories.pluck(:id)
    @book.category_ids -= category_ids_for_remove
    @new_categories = @categories.where.not(id: existing_category_id)
  end

  def validate_files
    status = true
    if params["book"]["book_cover_file"].present?
      book_cover_extention = params["book"]["book_cover_file"].original_filename.split(".").last
      status = status && ['gif','png','jpg','jpeg'].include?(book_cover_extention)
    end
    if params["book"]["audio"].present?
      audio_extention = params["book"]["audio"].original_filename.split(".").last
      status = status && ["mp3"].include?(audio_extention)
    end
    if params["book"]["short_audio_file"].present?
      audio_extention = params["book"]["short_audio_file"].original_filename.split(".").last
      status = status && ["mp3"].include?(audio_extention)
    end
    return true if status
    redirect_to books_path, notice: t("File are not valid!")
  end

  def validate_files_using_magic_number
    status = true
    if params["book"]["book_cover_file"].present?
      status = status && MagicNumber.is_real?(params["book"]["book_cover_file"].tempfile.path)
    end
    if params["book"]["audio"].present?
      status = status && MagicNumber.is_real?(params["book"]["audio"].tempfile.path)
    end
    if params["book"]["short_audio_file"].present?
      status = status && MagicNumber.is_real?(params["book"]["short_audio_file"].tempfile.path) 
    end
    return true if status
    redirect_to books_path, notice: t("MN File are not valid!") 
  end

  def upload_file_path_for(file, folder_name="public/audiobooksl/books")
    return if file.blank?
    dir = Rails.root.join(folder_name)
    Dir.mkdir(dir) unless Dir.exist?(dir)
    begin

app/controllers/web/books_controller.rb
class Web::BooksController < Web::WebApplicationController
  before_action :set_booth , except: [:all_books, :play_book_for_blind]
  before_action :fetch_categories, only: [:index]
  before_action :set_category, only: :category_search

  def index
    url = "#{ENV["API_BASE_URL"]}/web_api/booths/#{params[:booth_id]}/books"
    headers = {headers: {"Content-Type": "application/json"}, multipart: true, body: params.as_json}
    response = HTTParty.get(url, headers)
    response_body = JSON.parse(response.body) if response.body.present?
    if response_body.present? &&  response_body.dig("books").present? && response_body.dig("trending_books").present?
      @books = response_body["books"]["data"] rescue []
      @trending_books = response_body["trending_books"]["data"] rescue []
    end
  end

  def search
    url = "#{ENV["API_BASE_URL"]}/web_api/booths/#{params[:booth_id]}/books/search"
    headers = {headers: {"Content-Type": "application/json"},multipart: true, body: params.as_json}
    response = HTTParty.get(url, headers)
    response_body = JSON.parse(response.body) if response.body.present?
    if response_body.present? && response_body.dig("books").present?
      @books = response_body["books"]["data"] rescue []
    end
  end

  def category_search
    url = "#{ENV["API_BASE_URL"]}/web_api/booths/#{params[:booth_id]}/books/category_search"
    headers = {headers: {"Content-Type": "application/json"}, multipart: true, body: params.as_json}
    response = HTTParty.get(url, headers)
    response_body = JSON.parse(response.body) if response.body.present?
    if response_body.present? && response_body.dig("books").present?
      @books = response_body["books"]["data"] rescue []
      @total_books = response_body["total_books"]
      @total_time = response_body["total_time"]
      @total_author_count = response_body["total_author_count"]
    end
  end

  def show
    url = "#{ENV["API_BASE_URL"]}/web_api/booths/#{params[:booth_id]}/books/#{params[:id]}"
    headers = {headers: {"Content-Type": "application/json"}, multipart: true, body: params.as_json}
    response = HTTParty.get(url, headers)
    response_body = JSON.parse(response.body) if response.body.present?
    if response_body.present? &&  response_body.dig("book").dig("data").present?
      @book = response_body["book"]["data"]["attributes"]
      @qr_png_url = response_body["qr_png_link"]
    end
  end

  def accessibility_mode
    url = "#{ENV["API_BASE_URL"]}/web_api/booths/#{params[:booth_id]}/books/accessibility_mode"
    headers = {"Content-Type": "application/json"}
    response = HTTParty.get(url, headers: headers)
    response_body = JSON.parse(response.body) if response.body.present?
    if response_body.present? &&  response_body.dig("books").dig("data").present?
      @books = response_body["books"]["data"] rescue []
    end
  end

  def children_mode
    url = "#{ENV["API_BASE_URL"]}/web_api/booths/#{params[:booth_id]}/books/children_mode"
    headers = {"Content-Type": "application/json"}
    response = HTTParty.get(url, headers: headers)
    response_body = JSON.parse(response.body) if response.body.present?
    if response_body.present? &&  response_body.dig("books").dig("data").present?
      @books = response_body["books"]["data"] rescue []
    end
  end

  def all_books
    url = "#{ENV["API_BASE_URL"]}/web_api/all_books"
    headers = {"Content-Type": "application/json"}
    response = HTTParty.get(url, headers: headers)
    response_body = JSON.parse(response.body) if response.body.present?
    if response_body.present? &&  response_body.dig("books").dig("data").present?
      @books = response_body["books"]["data"] rescue []
    end
    render layout: false
  end

  def play_book_for_blind
    id = params[:id]
    url = "#{ENV["API_BASE_URL"]}/web_api/create_operation_for_blind"
    headers = {headers: {"Content-Type": "application/json"},multipart: true, body: params.as_json}
    response = HTTParty.get(url, headers)
    response_body = JSON.parse(response.body) if response.body.present?
    if response_body.present?
     operation_number = response_body["operation_number"]
    end
    redirect_to media_files_web_operation_path(id: operation_number)
  end

  def media_files
    @book = Book.where(id: params[:id]).includes(:book_files).first
    @book.update(last_listening_at: Time.now)
  end

  def update_listen_count
    render json: {message: "successfully save count"}
  end

  private

  def set_booth
    url = "#{ENV["API_BASE_URL"]}/web_api/booths/#{params[:booth_id]}"
    headers = {"Content-Type": "application/json"}
    response = HTTParty.get(url, headers: headers)
    response_body = JSON.parse(response.body) if response.body.present?
    if response_body.present? &&  response_body.dig("booth").dig("data").present?
      @booth = response_body["booth"]["data"]["attributes"]
    end
  end

  def ensure_booth_present?
    if @booth.blank?
      redirect_to booths_path, alert: t("booth_not_found")
    end
  end

  def fetch_categories
    url = "#{ENV["API_BASE_URL"]}/web_api/booths/#{params[:booth_id]}/categories"
    headers = {"Content-Type": "application/json"}
    response = HTTParty.get(url, headers: headers)
    response_body = JSON.parse(response.body) if response.body.present?
    if response_body.present? &&  response_body.dig("categories").present?
      @categories = response_body["categories"]["data"]
    end 
  end

  def set_category
    url = "#{ENV["API_BASE_URL"]}/web_api/booths/#{params[:booth_id]}/books/category_datail"
    headers = {"Content-Type": "application/json"}
    response = HTTParty.get(url, headers: headers, multipart: true, body: params.as_json)
    response_body = JSON.parse(response.body) if response.body.present?
    if response_body.present? &&  response_body.dig("category").dig("data").present?
      @category = response_body["category"]["data"]["attributes"]
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
  def total_time_in_minute(book)
    total = book.operations.sum(:listening_status)
    return Time.at(total).utc.strftime("%H:%M:%S")
  end
end

app/views/web/books/_ar_accessibility_mode.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title></title>
  <style>
    .access-overlay { height: 1227px; }
  </style>
  <%= javascript_include_tag "/h-scroll/jquery.mCustomScrollbar.concat.min.js"%>
</head>
<body>
  <div class="main-wrapper p-0" id="right-scroll">
  <div class="bg-overlay">
  <img src="<%= asset_url('top-acce-bg.png') %>" class="w-100" style="height:280px;"/>
  </div>
    <div class="_1R8mR">
      <div class="access-overlay">
      <div class="container">
        <div class="row justify-content-center align-items-center">
        <div class="login-box col-md-12 pt-5 mt-5">
                <div class="theme-form login-form text-center pt-5 mt-5">
                    <div>
                        <div class="avatar-logo">
                        <img src="<%= asset_url('logo-new.png') %>" />
                        </div>
                        <h1 class="mt-5 mb-0">مكتبة الكتب الصوتية</h1>
                        <h1 class="mt-2">Audiobooks Library</h1>
                    </div>
                </div>
        </div>
      </div>
    </div>
  </div>
  <main class="main">
    <div id="content-rd" class="content light">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
             <h2 class="text-right">الكتب الصوتية</h2>
          </div>
        </div>
        <div class="row mt-4">
          <% if @books.blank? %>
            No Record Found
          <% else %>
          <% @books.each do |book| %>
            <% book = book["attributes"] %>                
            <div class="col-md-6 col-lg-3 col-xl-3">
              <div id="Div4" class="single-product">
                <div class="part-1">
                  <span class="checkout-product-img">
                    <% img_url = book["cover"] rescue nil %>
                    <%= link_to web_booth_book_path(booth_id: @booth["number"], id: book["id"]), remote: true do %>
                      <img src="<%= img_url %>" class="rounded" />
                    <% end %>
                  </span>
                  <div class="first">

                    <div class="d-flex justify-content-between align-items-center">

                      <span class="discount-1"><%= book["language"].to_s.at(0) %></span>
                      <span class="wishlist"><%= Time.at(book["book_duration"].to_f).utc.strftime("%H:%M:%S") %> min <i class="fa fa-headphones pl-1" aria-hidden="true"></i></span>
                    </div>
                  </div>
                </div>
                <div class="part-2">
                  <% if params[:locale] == "ar" %>
                    <h3 class="product-title text-right"><%= book["arabic_title"] %></h3>
                    <h4 class="product-old-price text-right mt-3 mb-4"><%= book["arabic_author_name"] %></h4>
                    <h6 class="author text-right"><%= book["arabic_display_categories"] %></h6>
                  <% else %>
                    <h3 class="product-title text-right"><%= book["title"] %></h3>
                    <h4 class="product-old-price text-right mt-3 mb-4"><%= book["author_name"] %></h4>
                    <h6 class="author text-right"><%= book["display_categories"] %></h6>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
          <% end %>
        </div>

      </div>
    </div>
  </main>
    <footer>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-3">
            <%= link_to web_booth_path(id: @booth["number"]) do %>
              <img class="img-fluid" src="<%= asset_url('footer-logo-white.png') %>">
            <% end %>
          </div>
          <div class="col-md-9 text-right">
            <%= link_to web_booth_books_path(booth_id: @booth["number"]), class:"btn btn-light-grey btn-footer", remote: true do %>
              <img src="<%= asset_url('back-white.png') %>">
            <% end %>
            <% false && if params[:locale] == "en" || params[:locale] == nil %>
              <%= link_to category_search_web_booth_books_path(booth_id: @booth["number"], category_id: @categories.first.id, locale: :ar), class:"btn btn-light-grey btn-footer", remote: true do %>
                <img src="<%= asset_url('arabic.png') %>">
              <% end %>
            <% else %>
              <%= link_to category_search_web_booth_books_path(booth_id: @booth["number"], category_id: @categories.first.id), class:"btn btn-light-grey btn-footer", remote: true do %>
                <img src="<%= asset_url('eng-white.png') %>">
              <% end %>
            <% end %>

            <%= link_to accessibility_mode_web_booth_books_path(booth_id: @booth["number"]), remote: true, class:"btn btn-light-grey btn-footer" do %>
              <img src="<%= asset_url('access-white.png') %>">
            <% end %>

           <%= link_to  children_mode_web_booth_books_path(booth_id: @booth["number"]), class: "btn btn-light-grey btn-footer", remote: true do %>
              <img src="<%= asset_url('baby-white.png') %>">
            <% end %>
          </div>

        </div>
      </div>
    </footer>
  </div>
<!--   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
 -->
<script>
  (function ($){
    $.mCustomScrollbar.defaults.scrollButtons.enable = true; //enable scrolling buttons by default
    $.mCustomScrollbar.defaults.axis = "yx"; //enable 2 axis scrollbars by default

    $("#content-l").mCustomScrollbar();
    $("#content-rd").mCustomScrollbar({ theme: "rounded-dark" });
    $(".all-themes-switch a").click(function (e) {
      e.preventDefault();
      var $this = $(this),
      rel = $this.attr("rel"),
      el = $(".content");
      switch (rel) {
        case "toggle-content":
        el.toggleClass("expanded-content");
        break;
      }
    });
  })(jQuery);
</script>

 
</body>
</html>
<style>
  .isDisabled {
    pointer-events: none;
  }
  .access-overlay { height:935px;position:relative; }
  .bg-overlay {
    #  background-image: url("/assets/images/img1.jpeg") !important;
   
  }
  .single-product .part-1 {
    position: relative;
  }
  .single-product {
    width:200px;
  }
</style>

app/views/web/books/accessibility_mode.js.erb
$(".booth-show").html('')
$(".book-show-page").html("")
<% if params[:locale] == "ar" %>
    $(".book-index-page").html("<%= j render partial: "ar_accessibility_mode", locals: { books: @books, booth: @booth}  %>")
<% else %>
  $(".book-index-page").html("<%= j render partial: "ar_accessibility_mode", locals: { books: @books, booth: @booth}  %>")
<% end %>

app/views/web/books/all_books.html.erb
<div class="row">
  <div class="col-xl-12 col-md-6">  
    <div class="table-responsive mt-3">
      <table class="table table-bordered table-hover" id="table-ext-1">
        <thead>
          <tr>
            <th class="text-danger"><%= t('book_name')%></th>
          </tr>
        </thead>
        <tbody>
          <% if @books.blank? %>
            <tr><%= t('no_record_present') %></tr>
          <% else %>
            <% @books.each do |book|%>
              <% book = book["attributes"]%>
              <tr>
                <td><%= link_to "#{book["title"]}", web_play_book_for_blind_path(id: book["id"])  %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<style type="text/css">
  body {
    margin: 0;
    font-family: Effra;
    font-size: 1rem;
    font-weight: 500;
    letter-spacing: .3px;
    line-height: 1.52857;
    color: #656565;
    text-align: left;
    background-color: #fff;
    overflow:auto;
  }

  .table {
    width: 100%;
    margin-bottom: 1rem;
    color: #6d6c6c;
    font-size: 20;
  }

  .table td, .table th {
      padding: .15rem .65rem;
      vertical-align: top;
      border-top: 1px solid #eee;
      text-align: left;
  }

  .table thead th {
      vertical-align: bottom;
      border-bottom: 2px solid #c9c9c9;
  }

  .table tbody + tbody {
      border-top: 2px solid #c9c9c9;
  }

.table-sm td, .table-sm th {
    padding: .3rem;
}

.table-bordered, .table-bordered td, .table-bordered th {
    border: 1px solid #c9c9c9;
}

  .table-bordered thead td, .table-bordered thead th {
      border-bottom-width: 2px;
  }

</style> 

app/views/web/books/category_search.js.erb
$(".booth-show").html('')
$(".book-show-page").html("")
<% if params[:locale] == "ar" %>
    $(".book-index-page").html("<%= j render partial: "ar_category_detail", locals: { books: @books, booth: @booth}  %>")
<% else %>
  $(".book-index-page").html("<%= j render partial: "category_detail", locals: { books: @books, booth: @booth}  %>")
<% end %>

app/views/web/books/children_mode.js.erb
$(".booth-show").html('')
$(".book-show-page").html("")
<% if params[:locale] == "ar" %>
    $(".book-index-page").html("<%= j render partial: "ar_accessibility_mode", locals: { books: @books, booth: @booth}  %>")
<% else %>
  $(".book-index-page").html("<%= j render partial: "ar_accessibility_mode", locals: { books: @books, booth: @booth}  %>")
<% end %>

app/views/web/books/index.js.erb
$(".booth-show").html('')
$(".book-show-page").html("")
<% if params[:locale] == "ar" %>
  $(".book-index-page").html("<%= j render partial: "ar_book_index", locals: { books: @books, booth: @booth}  %>")
<% else %>
  $(".book-index-page").html("<%= j render partial: "book_index", locals: { books: @books, booth: @booth}  %>")
<% end %>

app/views/web/books/search.js.erb
$(".booth-show").html('')
$(".book-show-page").html("")
$(".book-index-page").html("<%= j render partial: "search", locals: { books: @books, booth: @booth}  %>")

app/views/web/books/show.js.erb
$(".book-index-page").html('')
<% if params[:locale] == "ar" %>
  $(".book-show-page").html("<%= j render partial: "ar_book_detail", locals: { book: @book, booth: @booth, qr_code: @qr_code}  %>")
<% else %>
  $(".book-show-page").html("<%= j render partial: "book_detail", locals: { book: @book, booth: @booth, qr_code: @qr_code}  %>")
<% end %>