config/routes.rb
Rails.application.routes.draw do
# mount ActiveStorage::Engine, at: "/audio" 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope :audio do
  root 'sessions#new'
  scope "(:locale)", locale: /en|ar|fr/ do 
    resources :sessions
    resources :homes
    resources :books do 
      get :setting, on: :member
      get :change_status, on: :member
    end
    resources :booths do
      get :setting, on: :member
    end
    resources :operations
    resources :categories  do
      get :setting, on: :member
    end
    resources :users do 
      get :setting, on: :member
      get :change_status, on: :member      
    end
    resources :reports

    get 'change_password/:auth_token',to: 'sessions#change_password', as: "change_password"
    get 'login', to: "sessions#new"

    namespace :web  do
      get "all_books", to: "books#all_books"
      get "play_book_for_blind", to: "books#play_book_for_blind"
      
      resources :booths, only: [:index, :show]  do
        resources :books, only: [:index, :show] do
          get :search, on: :collection
          get :category_search, on: :collection
          get :accessibility_mode, on: :collection
          get :children_mode, on: :collection
        end
      end
      resources :operations, only: [] do
        get :media_files, on: :member
        get :update_listen_count, on: :member
        put :save_feedback, on: :member
      end
    end
  end
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, except: [:create]
  before_action :set_user, except: [:index, :create]
  before_action :ensure_user_present?, except: [:index, :create]
  
  def index
    url = "#{ENV["API_BASE_URL"]}/api/users"
    headers = {"Content-Type": "application/json", "Authorization": "Bearer #{session[:token]}"}
    response = HTTParty.get(url, headers: headers)
    response_body = JSON.parse(response.body) if response.body.present?
    return render_token_invalid_error if response_body.present? && response_body["status_code"] == 301
    
    if response_body.present? &&  response_body.dig("users").dig("data").present?
      @users =  response_body["users"]["data"]
      @pagination_data =  response_body["users"]["meta"]
    end
      
    #per_page = params[:per_page] || 10
    #@users = User.all.order('created_at desc').paginate(page: params[:page], per_page: per_page)
  end

  def new
    @user = User.new
  end

  def show
    # @user = User.find_by(id: params[:id])
  end

  def edit
    # @user = User.find_by(id: params[:id])
  end

  def setting
    # @user = User.find_by(id: params[:id])
  end

  def create
    url = "#{ENV["API_BASE_URL"]}/api/users"
    headers = {headers: {"Content-Type": "application/json", "Authorization": "Bearer #{session[:token]}"},multipart: true, body: params.as_json}
    response = HTTParty.post(url, headers)
    response_body = JSON.parse(response.body) if response.body.present?
    return render_token_invalid_error if response_body.present? && response_body["status_code"] == 301
    
    if response_body.present? &&  response_body.dig("user").dig("data").present?
      redirect_to users_path
    end
  end

  def change_status
    @user = User.find_by(id: params[:id])
    status = @user.status == "Active" ? "Blocked" : "Active"
    @user.update(status: status)
    message = "User updated successfully!"
    redirect_to users_path, notice: message
  end

  def update
    url = "#{ENV["API_BASE_URL"]}/api/users/#{params[:id]}"
    headers = {headers: {"Content-Type": "application/json", "Authorization": "Bearer #{session[:token]}"},multipart: true, body: params.as_json}
    response = HTTParty.put(url, headers)
    response_body = JSON.parse(response.body) if response.body.present?
    return render_token_invalid_error if response_body.present? && response_body["status_code"] == 301
    
    if response_body.present? &&  response_body.dig("user").dig("data").present?
      redirect_to users_path
    end
  end

  def destroy
    url = "#{ENV["API_BASE_URL"]}/api/users/#{params[:id]}"
    headers = {"Content-Type": "application/json", "Authorization": "Bearer #{session[:token]}"}
    response = HTTParty.delete(url, headers: headers)
    response_body = JSON.parse(response.body) if response.body.present?
    return render_token_invalid_error if response_body.present? && response_body["status_code"] == 301
    
    if response_body.present? &&  response_body["status_code"] == 200
      message = t("user_destroy_message")
      redirect_to categories_path, notice: message
    else
      redirect_to categories_path, notice: t("something_went_wrong")
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:full_name, :mobile, :email, :gender, :role)
  end

  def set_user
    url = "#{ENV["API_BASE_URL"]}/api/users/#{params[:id]}"
    headers = {"Content-Type": "application/json", "Authorization": "Bearer #{session[:token]}"}
    response = HTTParty.get(url, headers: headers)
    response_body = JSON.parse(response.body) if response.body.present?
    return render_token_invalid_error if response_body.present? && response_body["status_code"] == 301
    
    if response_body.present? &&  response_body.dig("user").dig("data").present?
      @user = response_body["user"]["data"]["attributes"]
    end
  end

  def ensure_user_present?
    if @user.blank?
      message = t('user_not_present')
      redirect_to users_path, alert: message
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_action_modal.html.erb
<div class="modal fade" id="user-action-modal" tabindex="-1" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-body text-center mt-2 mb-3">
        <button class="close close-L" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

        <div class="mt-3">
          <%= link_to "<i class='fa fa-edit'></i>".html_safe, edit_user_path(id: user["id"]) ,remote: true, class: "modal-link-space btn btn-secondary-blue"%>
          <%= link_to "<i class='fa fa-eye'></i>".html_safe, user_path(id: user[
      "id"]) ,remote: true, class: "modal-link-space btn btn-secondary-blue"%>
          <%#= link_to "<i class='fa fa-trash text-danger'></i>".html_safe, user_path(id: user.id) ,method: "delete", remote: true, class: "modal-link-space"%>
          <% status = user["status"] == "Active" ? "Block": "Active"%>
          <% message = "Are you sure you want to #{status} this user"%>
          <% if user["status"] == "Active"%>
            <%= link_to "<i class='fa fa-lock'></i>".html_safe, change_status_user_path(id: user["id"]), data: { confirm: message }, class: "modal-link-space btn btn-secondary-blue"%>
          <% else %>
            <%= link_to "<i class='fa fa-unlock'></i>".html_safe, change_status_user_path(id: user["id"]) , data: { confirm: message }, class: "modal-link-space btn btn-secondary-blue"%>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>
<style type="text/css">
  .modal-link-space {margin-right: 10px;}
</style>

app/views/users/_detail.html.erb
<div class="modal fade" id="user-detail-modal" tabindex="-1" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
  <div class="modal-dialog modal-mdd">
    <div class="modal-content">
      <div class="modal-body">
        <h4 class="modal-title text-center" id="H1"><%= t('user_details')%></h4>
        <button class="close close-L" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <div class="row">
          <label for="example-text-input" class="col-md-4 col-form-label font-17"><%= t('user_name')%></label>
          <div class="col-md-6 col-form-label text-black font-17">
            <%= @user["full_name"] %>
          </div>                           
        </div>
        <div class="row">
          <label for="example-text-input" class="col-md-4 col-form-label font-17"><%= t('email')%></label>
          <div class="col-md-6 col-form-label text-black font-17">
            <%= @user["email"] %>
          </div>                           
        </div>
        <div class="row">
          <label for="example-text-input" class="col-md-4 col-form-label font-17"><%= t('phone_number')%></label>
          <div class="col-md-6 col-form-label text-black font-17">
            <%= @user["mobile"] %>
          </div>                           
        </div>
        <div class="row">
          <label for="example-text-input" class="col-md-4 col-form-label font-17"><%= t('authority')%></label>
          <div class="col-md-6 col-form-label text-black font-17">
            <%= @user["role"] %>
          </div>                           
        </div>
        <div class="row">
          <label for="example-text-input" class="col-md-4 col-form-label font-17"><%= t('status')%></label>
          <div class="col-md-6 col-form-label text-black font-17">
            <%= @user["status"] %>
          </div>                           
        </div>

      </div>

    </div>
  </div>
</div>

<style type="text/css">
  .modal-mdd {max-width: 500px;}
   .font-17{font-size: 17px}
    .text-black{color:#000;}
</style>

app/views/users/_edit_form_in_modal.html.erb
<div class="modal fade" id="user-edit-modal" tabindex="-1" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <h4 class="modal-title text-center" id="H1"><%= t('update_user')%></h4>
        <button class="close close-L" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

        <div class="mt-3">
          <%= form_with scope: :user, url: user_path(id: @user["id"]), method: :put do |f| %>
          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label"><%= t('name') %></label>
            <div class="col-md-10">
              <%= f.text_field :full_name, value: user['full_name'], class: "form-control text-center", placeholder: t('name') %>
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label"><%= t('email') %></label>
            <div class="col-md-10">
              <%= f.text_field :email, value: user['email'], class: "form-control text-center", placeholder: t('email') %>
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label"><%= t('phone_number') %></label>
            <div class="col-md-10">
              <%= f.text_field :mobile,value: user['mobile'], class: "form-control text-center", placeholder: t('phone_number') %>
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label"><%= t('authority_designation') %></label>
            <div class="col-md-10">
              <%= f.select :role, options_for_select(["Admin", "Approver", "operator"], selected: user["role"]), { include_blank: true},class: "custom-select custom-select-sm" %>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-lg-12 text-center">
              <div class="sub-button">
                <%= button_tag( :class => "btn btn-labeled btn-secondary-blue btn-rdius btn-rdius-13 font-bold") do %>
                  Update <span class='btn-label btn-label-right'><i class='fa fa-plus'></i></span>
                <% end %>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/users/edit.js.erb
$(".modal-backdrop").remove();
$("#user-action").html("");
$("#edit-modal").html("");
$("#edit-modal").html("<%= j render partial: "edit_form_in_modal", locals: { user: @user}  %>")
$("#user-edit-modal").modal("show");

app/views/users/index.html.erb
<div class="content-wrapper">
  <div class="content-heading">
    <div class="ml-auto">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#"><%= t('user') %></a></li>
          <li class="breadcrumb-item"><a href="#"><%= t('staff_management') %></a></li>
        </ol>
      </nav>
    </div>
  </div>
  <!-- START cards box-->
  <div class="row">
    <div class="col-xl-12 col-md-6">
      <!-- START card-->
      <button class="btn btn-labeled btn-secondary-blue btn-lg btn-rdius btn-rdius-13 font-bold" type="button" data-toggle="modal" data-target="#myModal"><%= t('add_user') %><span class="btn-label btn-label-right"><i class="fa fa-plus"></i></span></button>
      <div class="table-responsive mt-3">
        <table class="table table-bordered table-hover" id="table-ext-1">
          <thead>
            <tr>
              <th class="text-danger">#</th>
              <th class="text-danger"><%= t('name') %></th>
              <th class="text-danger"><%= t('email') %></th>
              <th class="text-danger"><%= t('phone_number') %></th>
              <th class="text-danger"><%= t('authority') %></th>
              <th class="text-danger"><%= t('status') %></th>
              <th class="text-danger"><%= t('last_login') %></th>
              <th class="text-danger"><%= t('setting') %></th>

            </tr>
          </thead>
          <tbody>
            <% if @users.blank? %>
              <tr><%= t('no_record_present')%></tr>
            <% else %>
              
              <% pagination_count = 0 %>
              <% if @pagination_data.present? %>
                <% page_no = @pagination_data["page"] || 0 %>
                <% per_page = @pagination_data["page_size"] || 0%>
                <% pagination_count = per_page * (page_no - 1) %>
              <% end %>


              <% @users.each_with_index do |user, i|%>
              <% user = user["attributes"]%>
              <tr>
                <td class="text-danger"><%= (pagination_count + i + 1) %></td>
                <td class="text-center"><%= user["full_name"] %></td>
                <td><%= user["email"] %></td>
                <td><%= user["mobile"] %></td>
                <td><%= user["role"] %></td>
                <td>
                  <% if user["status"] == "Active" %>
                    <label class="badge badge-green">Active</label> 
                  <% elsif user["status"] == "Invited" %>
                    <label class="badge badge-warning">Invited</label>
                  <% else %>
                    <label class="badge badge-danger">Blocked</label>
                  <% end %>
                </td>
                <td><%= Time.parse(user["last_login_at"]).strftime('%Y-%m-%d %l:%M %p') rescue nil %></td>
                <td><%= link_to "<i class='fa fa-cog fa-2x text-danger'></i>".html_safe, setting_user_path(id: user["id"]) ,remote: true%></td>
              </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="card-footer">
        <div class="d-flex">
          <% if @pagination_data.present? %>
<!--       <div>
            <div class="dataTables_info" id="datatable1_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
          </div> --> 
            <div class="ml-auto">
              <nav>
                <ul class="pagination pagination-sm">
                  <% if (@pagination_data["page"]- 1) == 0 %>
                    <li class="page-item disabled"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
                  <% else %>
                    <li class="page-item"><a class="page-link" href="<%= users_path(page: @pagination_data["page"]- 1) %>" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
                  <% end %>
                  <% if ( @pagination_data["page"] - 1 ) != 0 %>
                    <li class="page-item"><a class="page-link" href="<%= users_path(page: @pagination_data["page"]- 1) %>" aria-label="Previous"><span aria-hidden="true"><%= (@pagination_data["page"] - 1) %></span></a></li>
                  <% end %>

                  <li class="page-item"><a class="page-link" href="#" %><%= @pagination_data["page"] %></a></li>

                  <% if @pagination_data["total_pages"] >= ( @pagination_data["page"] + 1 )%>
                    <li class="page-item"><a class="page-link" href="<%= users_path(page: @pagination_data["page"] + 1) %>" aria-label="Previous"><span aria-hidden="true"><%= (@pagination_data["page"] + 1) %></span></a></li>
                  <% end %>
                  
                  <% if @pagination_data["page"] == @pagination_data["total_pages"] %>
                    <li class="page-item disabled"><a class="page-link" href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>
                  <% else %>
                    <li class="page-item"><a class="page-link" href="<%= users_path(page: @pagination_data["page"] + 1 ) %>" aria-label="Next"><span aria-hidden="true">»</span></a></li>
                  <% end %>
                
                </ul>
              </nav>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
  <!-- END cards box-->
</div>

<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <h4 class="modal-title text-center" id="myModalLabel"><%= t('add_user') %></h4>
        <button class="close close-L" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <%= form_with scope: :user, url: users_path, html: {id: "user-form"} do |f| %>
        <div class="mt-3">
          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label"><%= t('name') %></label>
            <div class="col-md-10">
              <%= f.text_field :full_name, class: "form-control text-center", placeholder: t('name') %>
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label"><%= t('email') %></label>
            <div class="col-md-10">
              <%= f.text_field :email, class: "form-control text-center", placeholder: t('email') %>
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label"><%= t('phone_number') %></label>
            <div class="col-md-10">
              <%= f.text_field :mobile, class: "form-control text-center", placeholder: t('phone_number') %>
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label"><%= t('authority_designation') %></label>
            <div class="col-md-10">
              <%= f.select :role, options_for_select(["Admin", "Approver", "operator"]), { include_blank: true},class: "custom-select custom-select-sm" %>
            </div>
          </div>
<!-- 
          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label"><%#= t('status') %></label>
            <div class="col-md-10">
              <%# status_options =  User.statuses.keys %>
              <%#= f.select :user_id, options_for_select(status_options), { include_blank: true},class: "custom-select custom-select-sm text-center" %>
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label "><%#= t('create_password') %></label>
            <div class="col-md-10">
              <%#= f.password_field :password, class: "form-control text-center", placeholder: t('create_password') %>
            </div>
          </div> -->

          <div class="form-group row">
            <div class="col-lg-12 text-center">
              <div class="sub-button">
                <%= button_tag( :class => "btn btn-labeled btn-secondary-blue btn-rdius btn-rdius-13 font-bold") do %>
                  <%= t('add') %> <span class='btn-label btn-label-right'><i class='fa fa-plus'></i></span>
                <% end %>
              </div>
            </div>
          </div>

        </div>
        <% end %>
      </div>

    </div>
  </div>
</div>
<div id="edit-modal"></div>
<div id="user-action"></div>
<div id="detail-modal"></div>

<script type="text/javascript">
  $("#user-form").validate({
    rules: {
    "user[full_name]": {required: true},
    "user[email]": {required: true},
    "user[mobile]": {required: true},
    "user[role]": {required: true},
    },
    messages: {
      "user[full_name]": "Name is requied",
      "user[email]": "Email is requied",
      "user[mobile]": "Mobile is requied",
      "user[role]": "Role is requied",
    }
  })
</script>

<script>
$(document).ready(function() {
    $('#table-ext-1').DataTable();
});
</script>

<style>
.dataTables_length {
    right: 590px;
}
</style>

app/views/users/setting.js.erb
$("#user-action").html("");
$("#user-action").html("<%= j render partial: "action_modal", locals: { user: @user}  %>")
$("#user-action-modal").modal("show");

app/views/users/show.js.erb
$(".modal-backdrop").remove();
$("#user-action").html("");
$("#detail-modal").html("");
$("#detail-modal").html("<%= j render partial: "detail", locals: { user: @user}  %>")
$("#user-detail-modal").modal("show");