config/routes.rb
Rails.application.routes.draw do
# mount ActiveStorage::Engine, at: "/audio" 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope :audio do
  root 'sessions#new'
  scope "(:locale)", locale: /en|ar|fr/ do 
    resources :sessions
    resources :homes
    resources :books do 
      get :setting, on: :member
      get :change_status, on: :member
    end
    resources :booths do
      get :setting, on: :member
    end
    resources :operations
    resources :categories  do
      get :setting, on: :member
    end
    resources :users do 
      get :setting, on: :member
      get :change_status, on: :member      
    end
    resources :reports

    get 'change_password/:auth_token',to: 'sessions#change_password', as: "change_password"
    get 'login', to: "sessions#new"

    namespace :web  do
      get "all_books", to: "books#all_books"
      get "play_book_for_blind", to: "books#play_book_for_blind"
      
      resources :booths, only: [:index, :show]  do
        resources :books, only: [:index, :show] do
          get :search, on: :collection
          get :category_search, on: :collection
          get :accessibility_mode, on: :collection
          get :children_mode, on: :collection
        end
      end
      resources :operations, only: [] do
        get :media_files, on: :member
        get :update_listen_count, on: :member
        put :save_feedback, on: :member
      end
    end
  end
  end 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in?
  before_action :set_category, except: [:index, :create]
  before_action :ensure_category_present?, except: [:index, :create]
  before_action :validate_files, only: [:create, :update]
  before_action :validate_files_using_magic_number, only: [:create, :update]
  include Rails.application.routes.url_helpers

  def index
    url = "#{ENV["API_BASE_URL"]}/api/categories"
    headers = {"Authorization": "Bearer #{session[:token]}"}
    response = HTTParty.get(url, headers: headers, body: params.as_json)
    response_body = JSON.parse(response.body) if response.body.present?
    return render_token_invalid_error if response_body.present? && response_body["status_code"] == 301

    
    if response_body.present? && response_body.dig("categories").present? && response_body.dig("categories").dig("data").present?
      @categories =  response_body["categories"]["data"]
      @pagination_data =  response_body["categories"]["meta"]
    end
  end

  # def create
  #     @store = Store.new({
  #     model_type: "Category",
  #     name: params[:category][:name],
  #     icon: params[:category][:icon],
  #     white_icon: params[:category][:white_icon]
  #     })
  #   @store.save
  #   url = "#{ENV["API_BASE_URL"]}/api/categories"
  #   data = {}
  #   data["category"] = {}
  #   if params["category"].present?
  #     data["category"] = params.require("category").permit(:name, :arabic_name, :french_name)
  #     data["category"]["dark"] = rails_blob_path(@store.icon, only_path: true) if params["category"]["icon"].present?
  #     data["category"]["white"] = rails_blob_path(@store.white_icon, only_path: true) if params["category"]["white_icon"].present?
  #     data["category"]["icon"] = File.open(params["category"]["icon"].tempfile.path) if params["category"]["icon"].present?
  #     data["category"]["white_icon"] = File.open(params["category"]["white_icon"].tempfile.path) if params["category"]["white_icon"].present?
  #   end
  #   headers = {headers: {"Content-Type": "application/json", "Authorization": "Bearer #{session[:token]}"},multipart: true, body: data}
  #   response = HTTParty.post(url, headers)
  #   response_body = JSON.parse(response.body) if response.body.present?
  #   @store.update(ref_id: response_body["category"]["data"]["id"].to_i)
  #   if response_body.present? &&  response_body.dig("category").dig("data").present?
  #     redirect_to categories_path
  #   end
  # end

  def create
    url = "#{ENV["API_BASE_URL"]}/api/categories"
    data = {}
    data["category"] = {}
    if params["category"].present?
      data["category"] = params.require("category").permit(:name, :arabic_name, :french_name)
      data["category"]["dark"] = upload_file_path_for(params["category"]["icon"]) if params["category"]["icon"].present?
      data["category"]["white"] = upload_file_path_for(params["category"]["white_icon"]) if params["category"]["white_icon"].present?
      data["category"]["icon"] = File.open(params["category"]["icon"].tempfile.path) if params["category"]["icon"].present?
      data["category"]["white_icon"] = File.open(params["category"]["white_icon"].tempfile.path) if params["category"]["white_icon"].present?
    end
    headers = {headers: {"Content-Type": "application/json", "Authorization": "Bearer #{session[:token]}"},multipart: true, body: data}
    response = HTTParty.post(url, headers)
    response_body = JSON.parse(response.body) if response.body.present?
    if response_body.present? &&  response_body.dig("category").dig("data").present?
      redirect_to categories_path
    end
  end

  def show
  end

  def edit
  end

  def setting
  end

  def update
    url = "#{ENV["API_BASE_URL"]}/api/categories/#{params[:id]}"
    data = {}
    data["category"] = {}
    if params["category"].present?
      data["category"] =  params.require("category").permit(:name, :arabic_name, :french_name)
      data["category"]["dark"] = upload_file_path_for(params["category"]["icon"]) if  params["category"]["icon"].present?
      data["category"]["white"] = upload_file_path_for(params["category"]["white_icon"]) if  params["category"]["white_icon"].present?
      data["category"]["icon"] = File.open(params["category"]["icon"].tempfile.path) if  params["category"]["icon"].present?
      data["category"]["white_icon"] = File.open(params["category"]["white_icon"].tempfile.path) if  params["category"]["white_icon"].present?
    end
    headers = {headers: {"Content-Type": "multipart/form-data", "Authorization": "Bearer #{session[:token]}"}, multipart: true, body: data}
    response = HTTParty.put(url, headers)
    response_body = JSON.parse(response.body) if response.body.present?
    return render_token_invalid_error if response_body.present? && response_body["status_code"] == 301

    if response_body.present? &&  response_body.dig("category").dig("data").present?
      redirect_to categories_path
    end
  end

  def destroy
    url = "#{ENV["API_BASE_URL"]}/api/categories/#{params[:id]}"
    headers = {"Content-Type": "application/json", "Authorization": "Bearer #{session[:token]}"}
    response = HTTParty.delete(url, headers: headers)
    response_body = JSON.parse(response.body) if response.body.present?
    return render_token_invalid_error if response_body.present? && response_body["status_code"] == 301

    if response_body.present? &&  response_body["status_code"] == 200
      message = t("category_destroy_message")
      redirect_to categories_path, notice: message
    else
      redirect_to categories_path, notice: t("something_went_wrong")
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :arabic_name, :french_name, :icon, :white_icon)
  end

  def set_category
    url = "#{ENV["API_BASE_URL"]}/api/categories/#{params[:id]}"
    headers = {"Content-Type": "application/json", "Authorization": "Bearer #{session[:token]}"}
    response = HTTParty.get(url, headers: headers)
    response_body = JSON.parse(response.body) if response.body.present?
    return render_token_invalid_error if response_body.present? && response_body["status_code"] == 301

    if response_body.present? &&  response_body.dig("category").dig("data").present?
      @category = response_body["category"]["data"]["attributes"]
    end
  end

  def ensure_category_present?
    if @category.blank?
      message = t('category_not_present')
      redirect_to categories_path, alert: message
    end
  end

  def validate_files
    status = true
    if params["category"]["icon"].present?
      icon_extention = params["category"]["icon"].original_filename.split(".").last
      status = status && ['png','jpg','jpeg'].include?(icon_extention)
    end
    if params["category"]["white_icon"].present?
      white_icon_extention = params["category"]["white_icon"].original_filename.split(".").last
      status = status && ['gif','png','jpg','jpeg'].include?(white_icon_extention)
    end
    return true if status
    redirect_to categories_path, notice: t("File are not valid!")
  end

  def validate_files_using_magic_number
    status = true
    if params["category"]["icon"].present?
      status = status && MagicNumber.is_real?(params["category"]["icon"].tempfile.path)
    end
    if params["category"]["white_icon"].present?
      status = status && MagicNumber.is_real?(params["category"]["white_icon"].tempfile.path)
    end
    return true if status

    redirect_to categories_path, notice: t("dsds File are not valid!") 
  end

  def upload_file_path_for(file, folder_name="public/audiobooksl/categories")
    return if file.blank?
    dir = Rails.root.join(folder_name)
    Dir.mkdir(dir) unless Dir.exist?(dir)
    begin
      path = dir.join(file.original_filename)
      File.open(path, 'wb') do |f|
        f.write(file.read)
      end
      return "/audiobooksl/categories/" + file.original_filename 
    rescue
      return nil
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_action_modal.html.erb
<div class="modal fade" id="cat-action-modal" tabindex="-1" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-body text-center">
        <button class="close close-L" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

        <div class="mt-3">
          <%= link_to "<i class='fa fa-edit'></i>".html_safe, edit_category_path(id:category["id"]) ,remote: true, class: "btn btn-secondary-blue modal-link-space"%>
          <%= link_to "<i class='fa fa-eye'></i>".html_safe, category_path(id:category["id"]) ,remote: true, class: "btn btn-secondary-blue modal-link-space"%>
          <%= link_to "<i class='fa fa-trash'></i>".html_safe, category_path(id: category["id"]) ,method: "delete", remote: true, class: "btn btn-secondary-blue modal-link-space"%>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/categories/_detail.html.erb
<div class="modal fade" id="category-detail-modal" tabindex="-1" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
  <div class="modal-dialog modal-mdd">
    <div class="modal-content">
      <div class="modal-body">
        <h4 class="modal-title text-center mb-3" id="H1"><%= t('category_details') %></h4>
        <button class="close close-L" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <div class="row">
          <label for="example-text-input" class="col-md-4 col-form-label"><%= t('category_name')%></label>
          <div class="col-md-6 col-form-label text-black font-17">
            <%= @category["name"] %>
          </div>                           
        </div>
        <div class="row">
          <label for="example-text-input" class="col-md-4 col-form-label"><%= t('category_arabic_name')%></label>
          <div class="col-md-6 col-form-label text-black font-17">
            <%= @category["arabic_name"] %>
          </div>                           
        </div>
        <div class="row">
          <label for="example-text-input" class="col-md-4 col-form-label"><%= t('category_french_name')%></label>
          <div class="col-md-6 col-form-label text-black font-17">
            <%= @category["french_name"] %>
          </div>                           
        </div>
        <div class="row">
          <label for="example-text-input" class="col-md-4 col-form-label"><%= t('booth_location')%></label>
          <div class="col-md-6 col-form-label text-black font-17">
            <%#= select_tag t('booth'), options_for_select(category.booths.pluck(:name, :id)), class: "custom-select custom-select-sm text-center"%>
          </div>                           
        </div>
      </div>

    </div>
  </div>
</div>
<style type="text/css">
  .modal-mdd {max-width: 500px;}
   .font-17{font-size: 17px}
    .text-black{color:#000;}
</style>

app/views/categories/_edit_form_in_modal.html.erb
<div class="modal fade" id="category-edit-modal" tabindex="-1" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-body">
        <h4 class="modal-title text-center" id="H1"><%= t('add_category')%></h4>
        <button class="close close-L" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

        <div class="mt-3">
          <%= form_with scope: :category, html: {id: "category_update_form"}, url: category_path(id: @category["id"]), method: :put do |f| %>
          <div class="form-group row">
               <label for="example-text-input" class="col-md-3 col-form-label text-center"><%= t('name')%></label>
            <div class="col-md-9">
              <%= f.text_field :name, value: @category["name"], class:"form-control text-center", placeholder: t('category_name') %>
            </div>                         
          </div>
          <div class="form-group row">
               <label for="example-text-input" class="col-md-3 col-form-label text-center"><%= t('arabic_name')%></label>
            <div class="col-md-9">
              <%= f.text_field :arabic_name, value: @category["arabic_name"], class:"form-control text-center", placeholder: t('arabic_name') %>
            </div>                         
          </div>
          <div class="form-group row">
               <label for="example-text-input" class="col-md-3 col-form-label text-center"><%= t('french_name')%></label>
            <div class="col-md-9">
              <%= f.text_field :french_name, value: @category["french_name"], class:"form-control text-center", placeholder: t('french_name') %>
            </div>                         
          </div>

          <div class="form-group row">
               <label for="example-text-input" class="col-md-3 col-form-label text-center"><%= t('icon')%></label>
            <div class="col-md-9">
              <%= f.file_field :icon, id: "update-category-icon"%>
            </div>                         
          </div>
          <div class="update-upload-preview" style="margin-top: 10px;">
            <% url = nil %>
            <% url = @category["icon_url"] if @category["icon_url"].present? %>
            <img  src= "<%= url %>" style="width: 30%; height: 30%;"/>
          </div>

          <div class="form-group row">
               <label for="example-text-input" class="col-md-3 col-form-label text-center"><%= t('white_icon')%></label>
            <div class="col-md-9">
              <%= f.file_field :white_icon, id: "update-category-white-icon"%>
            </div>                         
          </div>
          <div class="update-upload-white-preview" style="margin-top: 10px;">
            <% url = nil %>
            <% url = @category["white_icon_url"] if @category["white_icon_url"].present? %>
            <img src="<%= url %>" style="width: 30%; height: 30%;"/>
          </div>

          <div class="form-group row">
            <div class="col-md-12 text-center">
              <%= button_tag( :class => "btn btn-labeled btn-secondary-blue btn-rdius btn-rdius-13 font-bold") do %>
                <%= t('update') %> <span class="btn-label btn-label-right"><i class="fa fa-sync-alt"></i></span>              
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function(){
    var preview = $(".update-upload-preview img");
    var white_preview = $(".update-upload-white-preview img")

    $("#update-category-icon").change(function(event){
      var input = $(event.currentTarget);
      var file = input[0].files[0];
      var file_extention = $("#update-category-icon").val().split('.').pop().toLowerCase();
      if($.inArray(file_extention, ['gif','png','jpg','jpeg']) == -1) {
        alert('File has invalid extension only png, jpg, jpeg file is supported!');
        $("#update-category-icon").val('');
        return
      }
       var reader = new FileReader();
       reader.onload = function(e){
           image_base64 = e.target.result;
           preview.attr("src", image_base64);
       };
       reader.readAsDataURL(file);
    });

    $("#update-category-white-icon").change(function(event){
       var input = $(event.currentTarget);
       var file = input[0].files[0];
       var file_extention = $("#update-category-white-icon").val().split('.').pop().toLowerCase();
        if($.inArray(file_extention, ['gif','png','jpg','jpeg']) == -1) {
          alert('File has invalid extension only png, jpg, jpeg file is supported!');
          $("#update-category-white-icon").val('');
          return
        }
       var reader = new FileReader();
       reader.onload = function(e){
           image_base64 = e.target.result;
           white_preview.attr("src", image_base64);
       };
       reader.readAsDataURL(file);
    });
  });

</script>

app/views/categories/_form_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-body">
        <h4 class="modal-title text-center" id="myModalLabel">Add Category</h4>
        <button class="close close-L" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

        <div class="mt-3">
          <%= form_with scope: :category, url: categories_path, html: {id: "category_form"} do |f| %>
          <div class="form-group row">
               <label for="example-text-input" class="col-md-3 col-form-label text-center"><%= t('name')%></label>
            <div class="col-md-9">
              <%= f.text_field :name, class:"form-control text-center", placeholder: t('category_name') %>
            </div>                         
          </div>
          <div class="form-group row">
               <label for="example-text-input" class="col-md-3 col-form-label text-center"><%= t('arabic_name')%></label>
            <div class="col-md-9">
              <%= f.text_field :arabic_name, class:"form-control text-center", placeholder: t('arabic_name') %>
            </div>                         
          </div>
          <div class="form-group row">
            <label for="example-text-input" class="col-md-3 col-form-label text-center"><%= t('french_name')%></label>
            <div class="col-md-9">
              <%= f.text_field :french_name, class:"form-control text-center", placeholder: t('french_name') %>
            </div>                         
          </div>
          <div class="form-group row">
               <label for="example-text-input" class="col-md-3 col-form-label text-center"><%= t('icon')%></label>
            <div class="col-md-9">
              <%= f.file_field :icon, id: "category-icon"%>
            </div>                         
          </div>
          <div class="upload-preview" style="margin-top: 10px;">
            <img style="width: 30%; height: 30%;"/>
          </div>

          <div class="form-group row">
               <label for="example-text-input" class="col-md-3 col-form-label text-center"><%= t('white_icon')%></label>
            <div class="col-md-9">
              <%= f.file_field :white_icon, id: "category-white-icon"%>
            </div>                         
          </div>
          <div class="upload-white-preview" style="margin-top: 10px;">
            <img style="width: 30%; height: 30%;"/>
          </div>

          <div class="form-group row">
            <div class="col-md-12 text-center">
              <%= button_tag( :class => "btn btn-labeled btn-secondary-blue btn-rdius btn-rdius-13 font-bold") do %>
                <%= t('add')%> <span class='btn-label btn-label-right'><i class='fa fa-plus'></i></span>
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function(){
    var preview = $(".upload-preview img");
    var white_preview = $(".upload-white-preview img")

    $("#category-icon").change(function(event){
      var input = $(event.currentTarget);
      var file = input[0].files[0];
      var file_extention = $("#category-icon").val().split('.').pop().toLowerCase();
      if($.inArray(file_extention, ['gif','png','jpg','jpeg']) == -1) {
        alert('File has invalid extension only png, jpg, jpeg file is supported!');
        $("#category-icon").val('');
        return
      }
       var reader = new FileReader();
       reader.onload = function(e){
           image_base64 = e.target.result;
           preview.attr("src", image_base64);
       };
       reader.readAsDataURL(file);
    });

    $("#category-white-icon").change(function(event){
      var input = $(event.currentTarget);
      var file = input[0].files[0];
      var file_extention = $("#category-white-icon").val().split('.').pop().toLowerCase();
      if($.inArray(file_extention, ['gif','png','jpg','jpeg']) == -1) {
        alert('File has invalid extension only png, jpg, jpeg file is supported!');
        $("#category-white-icon").val('');
        return
      }
       var reader = new FileReader();
       reader.onload = function(e){
           image_base64 = e.target.result;
           white_preview.attr("src", image_base64);
       };
       reader.readAsDataURL(file);
    });
  });


</script>

app/views/categories/edit.js.erb
$(".modal-backdrop").remove();
$("#category-action").html("");
$("#edit-modal").html("");
$("#edit-modal").html("<%= j render partial: "edit_form_in_modal", locals: { category: @category}  %>")
$("#category-edit-modal").modal("show");

app/views/categories/index.html.erb
<div class="content-wrapper">
  <div class="content-heading">
    <div class="ml-auto">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#"><%= t('category') %></a></li>
        </ol>
      </nav>
    </div>
  </div>
  <!-- START cards box-->
  <div class="row">
    <div class="col-xl-12 col-md-6">
      <!-- START card-->
      <button class="btn btn-labeled btn-secondary-blue btn-lg btn-rdius btn-rdius-13 font-bold" type="button" data-toggle="modal" data-target="#myModal"><%= t('add_category') %> <span class="btn-label btn-label-right"><i class="fa fa-plus"></i></span></button>
      <div class="table-responsive mt-3">
        <table class="table table-bordered table-hover" id="table-ext-1">
          <thead>
            <tr>                                 
              <th class="text-danger">#</th>
              <th class="text-danger"><%= t('category_name') %></th> 
              <th class="text-danger"><%= t('arabic_name') %></th>
              <th class="text-danger"><%= t('french_name') %></th>
              <th class="text-danger"><%= t('icon') %></th>
              <th class="text-danger"><%= t('white_icon') %></th>  
              <th class="text-danger"><%= t('booth_location') %></th>
              <th class="text-danger"><%= t('data_of_category_creation') %></th>
              <th class="text-danger"><%= t('setting') %></th>
            </tr>
          </thead>
          <tbody>
            <% if @categories.blank? %>
              <tr><%= t('no_record_present') %></tr>
            <% else %>
              <% @categories.each_with_index do |category, i|%>
                <% category = category["attributes"]%>
                <tr>
                  <td class="text-danger"><%= ( i + 1) %></td>
                  <td><%= category["name"] %></td>
                  <td><%= category["arabic_name"] %></td>
                  <td><%= category["french_name"] %></td>
                  <td><img src="<%= category["logo"] if category["logo"].present? %>" class="cat-icon-img"></td>
                  <td><img src="<%= category["white_logo"] if category["white_logo"].present? %>" class="cat-icon-img"></td>
                  <td>
                    <div class="pl-2 pr-2">
                      <%= select_tag t('booth'), options_for_select(category["booths"]), class: "custom-select custom-select-sm text-center"%>
                    </div>
                  </td>
                  <td><%= Time.parse(category["created_at"]).strftime('%Y-%m-%d %l:%M %p') rescue nil %></td>
                  <td>
                    <%= link_to "<i class='fa fa-cog fa-2x text-danger'></i>".html_safe, setting_category_path(id:category["id"]) ,remote: true%>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="card-footer">
        <div class="d-flex">
          <% if @pagination_data.present? %>
<!--       <div>
            <div class="dataTables_info" id="datatable1_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
          </div> -->
            <div class="ml-auto">
              <nav>
                <ul class="pagination pagination-sm">
                  <% if (@pagination_data["page"]- 1) == 0 %>
                    <li class="page-item disabled"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
                  <% else %>
                    <li class="page-item"><a class="page-link" href="<%= categories_path(page: @pagination_data["page"]- 1) %>" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
                  <% end %>
                  <% if ( @pagination_data["page"] - 1 ) != 0 %>
                    <li class="page-item"><a class="page-link" href="<%= categories_path(page: @pagination_data["page"]- 1) %>" aria-label="Previous"><span aria-hidden="true"><%= (@pagination_data["page"] - 1) %></span></a></li>
                  <% end %>

                  <li class="page-item"><a class="page-link" href="#" %><%= @pagination_data["page"] %></a></li>

                  <% if @pagination_data["total_pages"] >= ( @pagination_data["page"] + 1 )%>
                    <li class="page-item"><a class="page-link" href="<%= categories_path(page: @pagination_data["page"] + 1) %>" aria-label="Previous"><span aria-hidden="true"><%= (@pagination_data["page"] + 1) %></span></a></li>
                  <% end %>
                  
                  <% if @pagination_data["page"] == @pagination_data["total_pages"] %>
                    <li class="page-item disabled"><a class="page-link" href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>
                  <% else %>
                    <li class="page-item"><a class="page-link" href="<%= categories_path(page: @pagination_data["page"] + 1 ) %>" aria-label="Next"><span aria-hidden="true">»</span></a></li>
                  <% end %>
                
                </ul>
              </nav>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
  <!-- END cards box-->
</div>

<%= render 'form_modal'%>

<div id="edit-modal"></div>
<div id="category-action"></div>
<div id="detail-modal"></div>

<style>
  .cat-icon-img {
    width: 35px;
    height: 35px;
  }
</style>
<script>
$(document).ready(function() {
    $('#table-ext-1').DataTable();
});
</script>

<style>
.dataTables_length {
    right: 590px;
}
</style>

app/views/categories/setting.js.erb
$("#category-action").html("");
$("#category-action").html("<%= j render partial: "action_modal", locals: { category: @category}  %>")
$("#cat-action-modal").modal("show");

app/views/categories/show.js.erb
$(".modal-backdrop").remove();
$("#category-action").html("");
$("#detail-modal").html("");
$("#detail-modal").html("<%= j render partial: "detail", locals: { category: @category}  %>")
$("#category-detail-modal").modal("show");