config/routes.rb
Rails.application.routes.draw do
# mount ActiveStorage::Engine, at: "/audio" 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope :audio do
  root 'sessions#new'
  scope "(:locale)", locale: /en|ar|fr/ do 
    resources :sessions
    resources :homes
    resources :books do 
      get :setting, on: :member
      get :change_status, on: :member
    end
    resources :booths do
      get :setting, on: :member
    end
    resources :operations
    resources :categories  do
      get :setting, on: :member
    end
    resources :users do 
      get :setting, on: :member
      get :change_status, on: :member      
    end
    resources :reports

    get 'change_password/:auth_token',to: 'sessions#change_password', as: "change_password"
    get 'login', to: "sessions#new"

    namespace :web  do
      get "all_books", to: "books#all_books"
      get "play_book_for_blind", to: "books#play_book_for_blind"
      
      resources :booths, only: [:index, :show]  do
        resources :books, only: [:index, :show] do
          get :search, on: :collection
          get :category_search, on: :collection
          get :accessibility_mode, on: :collection
          get :children_mode, on: :collection
        end
      end
      resources :operations, only: [] do
        get :media_files, on: :member
        get :update_listen_count, on: :member
        put :save_feedback, on: :member
      end
    end
  end
  end 
end

app/views/layouts/_ar_header.html.erb
<!-- top navbar-->
<header class="topnavbar-wrapper">
  <!-- START Top Navbar-->
  <nav class="navbar topnavbar">
    <!-- START navbar header-->
    <div class="navbar-header">
      <a class="navbar-brand" href="#/">
        <div class="brand-logo">
          <img class="img-fluid" src="<%= asset_url('logo.jpg') %>" alt="App Logo">
        </div>
        <!-- <div class="brand-logo-collapsed">
          <img class="img-fluid" src="../img/logo.png" alt="App Logo"></div>-->
      </a>
    </div>
    <!-- END navbar header-->

    <!-- START Right Navbar-->
    <ul class="navbar-nav flex-row">
      <!-- Search icon-->
      <% if false %>
      <li class="nav-item"><a class="nav-link" href="#" data-search-open=""><em class="icon-magnifier"></em></a></li>
      <!-- Fullscreen (only desktops)-->
      <li class="nav-item d-none d-md-block"><a class="nav-link" href="#" data-toggle-fullscreen=""><em class="fas fa-expand"></em></a></li>
      <% end %>
      <li>
        <%if request.url.split('/').to_a.include?("ar")%>     
          <div class="langbtn">
            <%= link_to "/audiobooksl/en/homes" do %>
            <span>English</span>
            <% end %>
          </div>  
        <%else%> 
          <div class="langbtn">
            <%= link_to "/audiobooksl/ar/homes" do %>
              <span>Arabic</span>
            <% end %>
          </div> 
        <%end%> 
      </li>

      <li class="nav-item">
        <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
        <a class="nav-link d-none d-md-block d-lg-block d-xl-block" href="#" data-trigger-resize="" data-toggle-state="aside-collapsed"><em class="fas fa-bars"></em></a>
        <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
        <a class="nav-link sidebar-toggle d-md-none" href="#" data-toggle-state="aside-toggled" data-no-persist="true"><em class="fas fa-bars"></em></a>
      </li>
      <li class="nav-item dropdown dropdown-list">
        <a class="nav-link dropdown-toggle profile-but" href="#" data-toggle="dropdown" type="button">
          <img _ngcontent-khx-c189="" src="<%= asset_url('Fr.png')%>" alt="Header Avatar" class="rounded-circle header-profile-user"><span _ngcontent-khx-c189="" class="d-none d-xl-inline-block ml-1">khaled</span><i _ngcontent-khx-c189="" class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
        </a>
        <!-- START Dropdown menu-->
        <div class="dropdown-menu dropdown-menu-right animated flipInX text-right">
          <a href="javascript: void(0);" class="dropdown-item">Profile <i class="icon-user align-middle ml-1"></i></a>
       <!--    <a href="javascript: void(0);" class="dropdown-item">My Wallet <i class="icon-wallet align-middle ml-1"></i></a>
          <a href="javascript: void(0);" class="dropdown-item d-block">Settings <i class="icon-settings align-middle ml-1"></i></a>
          <a href="javascript: void(0);" class="dropdown-item">Lock screen <i class="icon-lock align-middle ml-1"></i></a> -->
          <div class="dropdown-divider"></div>
         <%= link_to "#{t('logout')} <i class='icon-power align-middle mr-1 text-danger'></i>".html_safe, session_path(id: @current_user["id"]), method: :delete, data: { confirm: t('logout_confirm_msg') }, class: "dropdown-item text-danger" %>
        </div>
      </li>
    </ul>
    <!-- END Right Navbar-->
    <!-- START Search form-->
    <form class="navbar-form" role="search" action="search.html">
      <div class="form-group">
        <input class="form-control" type="text" placeholder="Type and hit enter ...">
        <div class="fas fa-times navbar-form-close" data-search-dismiss=""></div>
      </div>
      <button class="d-none" type="submit">Submit</button>
    </form>
    <!-- END Search form-->
  </nav>
  <!-- END Top Navbar-->
</header>
<!-- sidebar-->

app/views/layouts/_ar_side_menu_layout.html.erb
<!-- sidebar-->
<aside class="aside-container-R">
  <!-- START Sidebar (left)-->
  <div class="aside-inner">
    <nav class="sidebar" data-sidebar-anyclick-close="">
      <!-- START sidebar nav-->
      <ul class="sidebar-nav sidebar-text-R">
        <!-- START user info-->
        <li class="has-user-block">
          <div class="collapse" id="user-block">
            <div class="item user-block">
              <!-- User picture-->
              <div class="user-block-picture">
                <div class="user-block-status">
                  <img class="img-thumbnail rounded-circle" src="<%= asset_url('user/02.jpg')%>" alt="Avatar" width="60" height="60">
                  <div class="circle bg-success circle-lg"></div>
                </div>
              </div>
              <!-- Name and Job-->
              <div class="user-block-info"><span class="user-block-name">Hello, Mike</span><span class="user-block-role">Designer</span></div>
            </div>
          </div>
        </li>
        <!-- END user info-->
        <!-- Iterates over all sidebar items-->
        <li class="nav-heading "><span data-localize="sidebar.heading.HEADER">Main Navigation</span></li>
        <li class="<%= accessible?('homes-index') ? '' : 'hide' %>">
          <%= link_to "<em class='fa fa-desktop'></em><span data-localize='sidebar.nav.DASHBOARD'>#{t('dashboard')}</span>".html_safe, homes_path, title: t('dashboard') %> 
        </li>
        <li class="<%= accessible?('users-index') ? '' : 'hide' %>">
          <%= link_to "<em class='fa fa-user'></em><span>#{t('users')}</span>".html_safe, users_path, title: t('users')%>
        </li>
        <li class="<%= accessible?('books-index') ? '' : 'hide' %>">
          <%= link_to "<em class='fa fa-book'></em><span>#{t('audio_books')}</span>".html_safe, books_path, title: t('audio_books')%>
        </li>
        <li class="<%= accessible?('booths-index') ? '' : 'hide' %>">
          <%= link_to "<em class='fa fa-building'></em><span>#{t('booths')}</span>".html_safe, booths_path, title: t('booths')%>
        </li>
        <li class="<%= accessible?('operations-index') ? '' : 'hide' %>">
          <%= link_to "<em class='fa fa-project-diagram'></em><span data-localize='sidebar.nav.element.ELEMENTS'>#{t('operations')}</span>".html_safe, operations_path, title: t('operations')%>
        </li>
          <li class="<%= accessible?('reports-index') ? '' : 'hide' %>">
          <%= link_to "<em class='fa fa-file-code'></em><span data-localize='sidebar.nav.element.ELEMENTS'>#{t('report')}</span>".html_safe, reports_path, title: t('report')%>
        </li>
<!--         <li class="<%= accessible?('reports-index') ? '' : 'hide' %>"><a href="#forms" title="Forms" data-toggle="collapse">
          <em class="fa fa-file-code"></em><span data-localize="sidebar.nav.form.FORM">Reports</span>
          <i class="angle fa fa-chevron-right"></i>
        </a>
          <ul class="sidebar-nav sidebar-subnav collapse" id="forms">
            <li class=" "><a href="group-report.html" title="Wizard"><span>Group Report</span></a></li>
            <li class=" "><a href="author -teport.html" title="Upload"><span>Author Table</span></a></li>
            <li class=" "><a href="day-report.html" title="xEditable"><span>Day Table</span></a></li>
            <li class=" "><a href="time.html" title="Cropper"><span>Time Table</span></a></li>
          </ul>
        </li> -->
        <li class="<%= accessible?('categories-index') ? '' : 'hide' %>">
          <%= link_to "<em class='fa fa-cog'></em><span>#{t('category')}</span>
          <i class='angle fa fa-chevron-right'></i>".html_safe, categories_path, title: t('category')%> 
        </li>

        <!-- <li class=" "><a href="#multilevel" title="Multilevel" data-toggle="collapse"><em class="far fa-folder-open"></em><span>Multilevel</span></a>
          <ul class="sidebar-nav sidebar-subnav collapse" id="multilevel">
            <li class="sidebar-subnav-header">Multilevel</li>
            <li class=" "><a href="#level1" title="Level 1" data-toggle="collapse"><span>Level 1</span></a>
              <ul class="sidebar-nav sidebar-subnav collapse" id="level1">
                <li class="sidebar-subnav-header">Level 1</li>
                <li class=" "><a href="multilevel-1.html" title="Level1 Item"><span>Level1 Item</span></a></li>
                <li class=" "><a href="#level2" title="Level 2" data-toggle="collapse"><span>Level 2</span></a>
                  <ul class="sidebar-nav sidebar-subnav collapse" id="level2">
                    <li class="sidebar-subnav-header">Level 2</li>
                    <li class=" "><a href="#level3" title="Level 3" data-toggle="collapse"><span>Level 3</span></a>
                      <ul class="sidebar-nav sidebar-subnav collapse" id="level3">
                        <li class="sidebar-subnav-header">Level 3</li>
                        <li class=" "><a href="multilevel-3.html" title="Level3 Item"><span>Level3 Item</span></a></li>
                      </ul>
                    </li>
                  </ul>
                </li>
              </ul>
            </li>
          </ul>
        </li>-->
      </ul>
      <!-- END sidebar nav-->
    </nav>
  </div>
  <!-- END Sidebar (left)-->
</aside>

app/views/layouts/_en_header.html.erb
<!-- top navbar-->
<header class="topnavbar-wrapper">
    <!-- START Top Navbar-->
    <nav class="navbar topnavbar">
        <!-- START navbar header-->
        <div class="navbar-header">
            <a class="navbar-brand" href="#/">
                <div class="brand-logo">
                    <img class="img-fluid" src="<%= asset_url('logo.jpg')%>" alt="Logo"/>
                </div>
                <!-- <div class="brand-logo-collapsed">
                    <img class="img-fluid" src="../img/logo.png" alt="App Logo"></div>-->
            </a>
        </div>
        <!-- END navbar header-->
        <ul class="navbar-nav mr-auto flex-row">
            <li class="nav-item">
                <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
                <a class="nav-link d-none d-md-block d-lg-block d-xl-block" href="#" data-trigger-resize="" data-toggle-state="aside-collapsed"><em class="fas fa-bars"></em></a>
                <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
                <a class="nav-link sidebar-toggle d-md-none" href="#" data-toggle-state="aside-toggled" data-no-persist="true"><em class="fas fa-bars"></em></a>
            </li>
        </ul>
        <!-- START Right Navbar-->
        <ul class="navbar-nav flex-row">
            <!-- Search icon-->
            <% if false %>
            <li class="nav-item d-none d-md-block"><a class="nav-link" href="#" data-search-open=""><em class="fa fa-search"></em></a></li>
            <!-- Fullscreen (only desktops)-->
            <li class="nav-item d-none d-md-block"><a class="nav-link" href="#" data-toggle-fullscreen=""><em class="fas fa-expand"></em></a></li>
            <% end %>
            
        <li>
            <%if request.url.split('/').to_a.include?("ar")%>     
                <div class="langbtn">
                    <%= link_to "/audiobooksl/en/homes" do %>
                        <span>English</span>
                    <% end %>
                </div>  
            <%else%> 
                <div class="langbtn">
                    <%= link_to "/audiobooksl/ar/homes" do %>
                        <span>Arabic</span>
                    <% end %>
                </div> 
            <%end%> 
        </li>


            <li class="nav-item dropdown dropdown-list">
                <a class="nav-link dropdown-toggle profile-but" href="#" data-toggle="dropdown" type="button">
                    <img _ngcontent-khx-c189="" src="<%= asset_url('Fr.png') %>" alt="Header Avatar" class="rounded-circle header-profile-user"><span _ngcontent-khx-c189="" class="d-none d-xl-inline-block ml-1">Khaled</span><i _ngcontent-khx-c189="" class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </a>
                <!-- START Dropdown menu-->
                <div class="dropdown-menu dropdown-menu-right animated flipInX">
                    <a href="javascript: void(0);" class="dropdown-item"><i class="fa fa-user align-middle mr-2"></i>Profile </a>
                    <!-- <a href="javascript: void(0);" class="dropdown-item"><i class="fa fa-wallet align-middle mr-2"></i>My Wallet </a>
                    <a href="javascript: void(0);" class="dropdown-item d-block"><i class="fa fa-cog align-middle mr-2"></i>Settings </a>
                    <a href="javascript: void(0);" class="dropdown-item"><i class="fa fa-lock align-middle mr-2"></i>Lock screen </a> -->
                    <div class="dropdown-divider"></div>
                    <%= link_to "<i class='fa fa-sign-out-alt align-middle text-danger mr-2'></i> #{t('logout')}".html_safe, session_path(id: @current_user["id"]), method: :delete, data: { confirm: t('logout_confirm_msg') }, class: "dropdown-item text-danger" %>
                </div>
            </li>
        </ul>
        <!-- END Right Navbar-->
        <!-- START Search form-->
        <form class="navbar-form" role="search" action="search.html">
            <div class="form-group">
                <input class="form-control" type="text" placeholder="Type and hit enter ...">
                <div class="fas fa-times navbar-form-close" data-search-dismiss=""></div>
            </div>
            <button class="d-none" type="submit">Submit</button>
        </form>
        <!-- END Search form-->
    </nav>
    <!-- END Top Navbar-->
</header>

app/views/layouts/_en_side_menu_layout.html.erb
 <!-- sidebar-->
<aside class="aside-container" id="side-menu">
  <!-- START Sidebar (left)-->
  <div class="aside-inner">
    <nav class="sidebar" data-sidebar-anyclick-close="">
      <!-- START sidebar nav-->
      <ul class="sidebar-nav">
        <!-- START user info-->
        <li class="has-user-block">
          <div class="collapse" id="user-block">
            <div class="item user-block">
              <!-- User picture-->
              <div class="user-block-picture">
                <div class="user-block-status">
                  <img class="img-thumbnail rounded-circle" src="<%= asset_url('user/02.jpg')%>" alt="Avatar" width="60" height="60">
                  <div class="circle bg-success circle-lg"></div>
                </div>
              </div>
              <!-- Name and Job-->
              <div class="user-block-info"><span class="user-block-name">Hello, Mike</span><span class="user-block-role">Designer</span></div>
            </div>
          </div>
        </li>
        <!-- END user info-->
        <!-- Iterates over all sidebar items-->
        <li class="nav-heading "><span data-localize="sidebar.heading.HEADER">Main Navigation</span></li>
        <li class="<%= accessible?('homes-index') ? '' : 'hide' %>">
          <%= link_to "<em class='fa fa-desktop'></em><span data-localize='sidebar.nav.DASHBOARD'>#{t('dashboard')}</span>".html_safe, homes_path, title: t('dashboard') %>
        </li>
        <li class="<%= accessible?('users-index') ? '' : 'hide' %>">
          <%= link_to "<em class='fa fa-user'></em><span>#{t('users')}</span>".html_safe, users_path, title: t('users')%>
        </li>
        <li class="<%= accessible?('books-index') ? '' : 'hide' %>">
          <%= link_to "<em class='fa fa-book'></em><span>#{t('audio_books')}</span>".html_safe, books_path, title: t('audio_books')%>
        </li>
        <li class="<%= accessible?('booths-index') ? '' : 'hide' %>">
          <%= link_to "<em class='fa fa-building'></em><span>#{t('booths')}</span>".html_safe, booths_path, title: t('booths')%>
        </li>
        <li class="<%= accessible?('operations-index') ? '' : 'hide' %>">
        <%= link_to "<em class='fa fa-project-diagram'></em><span data-localize='sidebar.nav.element.ELEMENTS'>#{t('operations')}</span>".html_safe, operations_path, title: t('operations')%>
        </li>
        <li class="<%= accessible?('reports-index') ? '' : 'hide' %>">
          <%= link_to "<em class='fa fa-file-code'></em><span data-localize='sidebar.nav.element.ELEMENTS'>#{t('report')}</span>".html_safe, reports_path, title: t('report')%>
        </li>
<!--         <li class="<%= accessible?('reports-index') ? '' : 'hide' %>"><a href="#report" title="Report" data-toggle="collapse">
          <em class="fa fa-file-code"></em><span data-localize="sidebar.nav.form.FORM">Reports</span>
          <i class="angle fa fa-chevron-right"></i>
        </a>
          <ul class="sidebar-nav sidebar-subnav collapse" id="report">                            
            <li class=" "><a href="group-report.html" title="Wizard"><span>Group Report</span></a></li>
            <li class=" "><a href="author-report.html" title="Upload"><span>Author Report</span></a></li>
            <li class=" "><a href="day-report.html" title="xEditable"><span>Day Table</span></a></li>
            <li class=" "><a href="time.html" title="Cropper"><span>Time Table</span></a></li>
          </ul>
        </li> -->
        <li class="<%= accessible?('categoies-index') ? '' : 'hide' %>">
          <%= link_to "<em class='fa fa-cog'></em><span>#{t('category')}</span>
          <i class='angle fa fa-chevron-right'></i>".html_safe, categories_path, title: t('category')%>
        </li>
      </ul>
      <!-- END sidebar nav-->
    </nav>
  </div>
  <!-- END Sidebar (left)-->
</aside>

app/views/layouts/_footer.html.erb
<footer class="footer-container text-center"><span><!-- &copy; 2021 - Angle --></span></footer>

app/views/layouts/_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <h4 class="modal-title text-center" id="myModalLabel"><%= t('adding_booth') %></h4>
        <button class="close close-L" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <%= form_with model: @booth do|f| %>
        <div class="mt-3">
          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label text-center"><%= t('name')%></label>
            <div class="col-md-10">
              <%= f.text_field :name, class: "form-control text-center", placeholder: t('name') %>
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label text-center"><%= t('city')%></label>
            <div class="col-md-10">
              <%= f.select :city, options_for_select(["Delhi","Lucknow"]), {include_blank: true},class: "custom-select custom-select-sm text-center" %>
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label text-center"><%= t('address')%></label>
            <div class="col-md-10">
              <%= f.text_field :address, class: "form-control text-center", placeholder: t("address") %>
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label text-center"><%= t('coordinates')%></label>
            <div class="col-md-10">
              <%= f.text_field :coordinate, class: "form-control text-center", placeholder: t("coordinates") %>
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label text-center"><%= t('communicate_with')%></label>
            <div class="col-md-10">
              <input class="form-control text-center" type="email" placeholder="Mohamed shihri">
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label text-center"><%= t('phone_number')%></label>
            <div class="col-md-10">
              <%= f.text_field :phone_number, class: "form-control text-center", placeholder: "0509050803" %>
            </div>
          </div>

          <div class="form-group row">
             <label for="example-text-input" class="col-md-2 col-form-label text-center"><%= t('category_name')%></label>
            <div class="col-md-10">
              <%= f.text_field :category_name, class: "form-control text-center", placeholder: t("category_name") %>
            </div>
             
          </div>

          <div class="form-group row">
            <div class="col-md-12 text-center">
              <%= button_tag( :class => "btn btn-labeled btn-secondary-blue btn-rdius btn-rdius-13 font-bold") do %>
                Add <span class='btn-label btn-label-right'><i class='fa fa-plus'></i></span>
              <% end %>
            </div>
          </div>

        </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

<div class="modal fade" id="update-booth" tabindex="-1" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <h4 class="modal-title text-center" id="H1">Update Booth</h4>
        <button class="close close-L" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>

        <div class="mt-3">
          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label text-center">Name</label>
            <div class="col-md-10">
              <input class="form-control text-center" type="email" placeholder="Riyadh Park">
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label text-center">City</label>
            <div class="col-md-10">
              <select class="custom-select custom-select-sm text-center">
                <option selected="">Riyadh</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
              </select>
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label text-center">Address</label>
            <div class="col-md-10">
              <input class="form-control text-center" type="email" placeholder="Riyadh park, second floor behind Nando’s Restaurant">
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label text-center">Coordinates</label>
            <div class="col-md-10">
              <input class="form-control text-center" type="email" placeholder="24.7070803,46.6905646">
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label text-center">Communicate with</label>
            <div class="col-md-10">
              <input class="form-control text-center" type="email" placeholder="Mohamed shihri">
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label text-center">Phone number</label>
            <div class="col-md-10">
              <input class="form-control text-center" type="email" placeholder="0509050803">
            </div>
          </div>

          <div class="form-group row">
            <label for="example-text-input" class="col-md-2 col-form-label text-center">Category Name</label>
            <div class="col-md-10">
              <input class="form-control text-center" type="email" placeholder="Category Name">
            </div>
            
          </div>

          <div class="form-group row">
            <div class="col-md-12 text-center">
              <button class="btn btn-labeled btn-secondary-blue btn-rdius btn-rdius-13 font-bold" type="button">Update <span class="btn-label btn-label-right"><i class="fa fa-sync-alt"></i></span></button>
              <button class="btn btn-labeled btn-secondary-blue btn-rdius btn-rdius-13 font-bold ml-2" type="button">Cancel <span class="btn-label btn-label-right"><i class="fa fa-times"></i></span></button>
            </div>
          </div>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AudioLibrary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%# <base href = "https://culturalhub.moc.gov.sa/audiobooksl/" /> %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- This refers to app/javascript/stylesheets/application.scss-->
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.min.js", async: true %>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.4/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.11.4/datatables.min.js"></script>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <% if not params[:controller] == "sessions" ||  params["controller"].start_with?("web") %>
    <%# if current_user.present? %>
      <div class="wrapper">
        <% if params["locale"].blank? || params[:locale] == "en" %>
          <%= render 'layouts/en_header' %>
          <%= render 'layouts/en_side_menu_layout'%>
          <section class="section-container">
            <%= yield %>
          </section>
          <%= render 'layouts/footer'%>
        <% elsif params[:locale] == "ar" %>
          <%= render 'layouts/ar_header' %>
          <%= render 'layouts/ar_side_menu_layout'%>
          <section class="section-container-R">
            <%= yield %>
          </section>
          <%= render 'layouts/footer'%>
        <% end %>
      </div>
      <% else %>
        <%= yield %>
      <% end %>
    <!-- put yield in a div Wrapper class beacuse all header and navbar define in wrapper class -->
    <!-- And also section-container is contain different class for css so that's why section is also define here -->
  </body>
</html>
<script type="text/javascript">
  $(document).ready(function(){
  $(".sidebar-nav>li").each(function() {
    var navItem = $(this);
    if (navItem.find("a").attr("href") == location.pathname) {
      navItem.addClass("active");
    }
  });
  setTimeout(function(){
      $(".alert").hide();
    }, 10000);  
});  
</script>

app/views/layouts/ar_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Audio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <%= render 'layouts/ar_header' %>
      <%= render 'layouts/ar_side_menu_layout'%>
      <section class="section-container-R">
        <%= yield %>
      </section>
      <%= render 'layouts/footer'%>
    </div>
  </body>
</html>

app/views/layouts/eng_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Audio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <%= render 'layouts/en_header' %>
      <%= render 'layouts/en_side_menu_layout'%>
      <section class="section-container">
        <%= yield %>
      </section>
      <%= render 'layouts/footer'%>
    </div>
  </body>
</html>